### ISSUE TITLE
REPL does not enable initialization

### ISSUE THREAD

**Issue by gebner** [leanprover-community/repl#1]
When importing modules, you need to enable initializer execution (using `enableInitializersExecution`) otherwise attributes, etc. won't work.

Input:
```json
{"cmd": "import Lake open Lake DSL\npackage REPL"}
```

Output:
```json
{"sorries": [],
 "messages":
 [{"severity": "error",
   "pos": {"line": 2, "column": 0},
   "endPos": {"line": 2, "column": 12},
   "data": "unknown attribute [package]"}],
 "env": 0}
```

**Comment by semorrison** [comment]
Fixed in https://github.com/leanprover-community/repl/commit/11daea2ee742b512cc94b4a280849485254e592a
