### ISSUE TITLE
Is it possible to query the goal texts in a tactic state?

### ISSUE THREAD

**Issue by UltimatePea** [leanprover-community/repl#19]
From README it seems that the only data associated with a proof state is its goal type. Is it possible to query premises of a tactic state?

**Comment by semorrison** [comment]
Yes, all hypotheses are included in the goal states, appearing before the turnstile symbol `⊢`.

The examples in the README don't have hypotheses!

**Comment by semorrison** [comment]
@UltimatePea, thank you for pointing this out! That was definitely an oversight, and is now fixed.
