### ISSUE TITLE
Infinite recursion on empty input

### ISSUE THREAD

**Issue by gebner** [leanprover-community/repl#2]
I carelessly piped a single line into the repl and got infinite recursion in `getLines`.  Input:
```bash
echo '{"cmd": "#eval \"Hello, world!\""}' | ./run
```

**Comment by semorrison** [comment]
Fixed (I discovered the same thing) in https://github.com/leanprover-community/repl/commit/11daea2ee742b512cc94b4a280849485254e592a.
