### ISSUE TITLE
Unable to run the repl

### ISSUE THREAD

**Issue by orenelbaum** [leanprover-community/repl#54]
When I run `lake exe repl` I get `error: unknown executable repl`.
I have Lake version 5.0.0-702c31b and Lean version 4.10.0-rc2.

**Comment by vadimkantorov** [comment]
Same error: `error: unknown executable repl`

`Lake version 5.0.0-128a1e6 (Lean version 4.16.0)`

**Comment by vadimkantorov** [comment]
Is it because of too old lean version?
